export const Input = [
  {
    label: '占位提示',
    tag: 'n-input',
    tagType: 'Input',
    __vModel__: '__config__.placeholder',
    __layout__: {},
    __config__: {
      placeholder: '请输入占位提示',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '前缀',
    tag: 'n-input',
    tagType: 'Input',
    __vModel__: '__slot__.preLabel',
    __layout__: {},
    __config__: {
      placeholder: '请输入前缀',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '后缀',
    tag: 'n-input',
    tagType: 'Input',
    __vModel__: '__slot__.sufLabel',
    __layout__: {},
    __config__: {
      placeholder: '请输入后缀',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '前图标',
    tag: 'select-icon',
    tagType: 'SelectIcon',
    __vModel__: '__slot__.default.prefix',
    __layout__: {},
    __config__: {
      placeholder: '请选择前图标',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '后图标',
    tag: 'select-icon',
    tagType: 'SelectIcon',
    __vModel__: '__slot__.default.suffix',
    __layout__: {},
    __config__: {
      placeholder: '请选择后图标',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '最大长度',
    tag: 'input-unit',
    tagType: 'InputUnit',
    __vModel__: '__config__.maxlength',
    __layout__: {},
    __config__: {
      placeholder: '允许最大字符长度',
      suffix: '字符',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '是否圆角',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.round',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
  {
    label: '显示字数',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.showCount',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
  {
    label: '能否清空',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.clearable',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
  {
    label: '是否只读',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.readonly',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
];
export const Textarea = [
  {
    label: '占位提示',
    tag: 'n-input',
    tagType: 'Input',
    __vModel__: '__config__.placeholder',
    __layout__: {},
    __config__: {
      placeholder: '请输入占位提示',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '最小行数',
    tag: 'n-input-number',
    tagType: 'Number',
    __vModel__: '__config__.autosize.minRows',
    __layout__: {},
    __config__: {
      defaultValue: 3,
      buttonPlacement: 'both',
      min: 1,
      max: 99,
      step: 0,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '最大行数',
    tag: 'n-input-number',
    tagType: 'Number',
    __vModel__: '__config__.autosize.maxRows',
    __layout__: {},
    __config__: {
      defaultValue: 3,
      buttonPlacement: 'both',
      min: 1,
      max: 99,
      step: 0,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '最大长度',
    tag: 'input-unit',
    tagType: 'InputUnit',
    __vModel__: '__config__.maxlength',
    __layout__: {},
    __config__: {
      placeholder: '允许最大字符长度',
      suffix: '字符',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '显示字数',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.showCount',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
  {
    label: '能否清空',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.clearable',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
  {
    label: '是否只读',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.readonly',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
];
export const Password = [
  {
    label: '占位提示',
    tag: 'n-input',
    tagType: 'Input',
    __vModel__: '__config__.placeholder',
    __layout__: {},
    __config__: {
      placeholder: '请输入占位提示',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '前缀',
    tag: 'n-input',
    tagType: 'Input',
    __vModel__: '__slot__.preLabel',
    __layout__: {},
    __config__: {
      placeholder: '请输入前缀',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '后缀',
    tag: 'n-input',
    tagType: 'Input',
    __vModel__: '__slot__.sufLabel',
    __layout__: {},
    __config__: {
      placeholder: '请输入后缀',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '前图标',
    tag: 'select-icon',
    tagType: 'SelectIcon',
    __vModel__: '__slot__.default.prefix',
    __layout__: {},
    __config__: {
      placeholder: '请选择前图标',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '关闭图标',
    tag: 'select-icon',
    tagType: 'SelectIcon',
    __vModel__: '__slot__.default.password-invisible-icon',
    __layout__: {},
    __config__: {
      placeholder: '密码关闭时图标',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '打开图标',
    tag: 'select-icon',
    tagType: 'SelectIcon',
    __vModel__: '__slot__.default.password-visible-icon',
    __layout__: {},
    __config__: {
      placeholder: '密码打开时图标',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '最大长度',
    tag: 'input-unit',
    tagType: 'InputUnit',
    __vModel__: '__config__.maxlength',
    __layout__: {},
    __config__: {
      placeholder: '允许最大字符长度',
      suffix: '字符',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '是否圆角',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.round',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
  {
    label: '能否清空',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.clearable',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
  {
    label: '是否只读',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.readonly',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
];
export const Number = [
  {
    label: '占位提示',
    tag: 'n-input',
    tagType: 'Input',
    __vModel__: '__config__.placeholder',
    __layout__: {},
    __config__: {
      placeholder: '请输入占位提示',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '前图标',
    tag: 'select-icon',
    tagType: 'SelectIcon',
    __vModel__: '__slot__.default.prefix',
    __layout__: {},
    __config__: {
      placeholder: '请选择前图标',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '后图标',
    tag: 'select-icon',
    tagType: 'SelectIcon',
    __vModel__: '__slot__.suffix',
    __layout__: {},
    __config__: {
      placeholder: '请选择后图标',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '增加按钮',
    tag: 'select-icon',
    tagType: 'SelectIcon',
    __vModel__: '__slot__.add-icon',
    __layout__: {},
    __config__: {
      placeholder: '增加按钮的图标',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '减少按钮',
    tag: 'select-icon',
    tagType: 'SelectIcon',
    __vModel__: '__slot__.minus-icon',
    __layout__: {},
    __config__: {
      placeholder: '减少按钮的图标',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '最大值',
    tag: 'n-input',
    tagType: 'Input',
    __vModel__: '__config__.max',
    __layout__: {},
    __config__: {
      allowInput: (val) => !val || /^[-]?\d+(\.\d+)?$/.test(val),
      placeholder: '允许最大值',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '最小值',
    tag: 'n-input',
    tagType: 'Input',
    __vModel__: '__config__.min',
    __layout__: {},
    __config__: {
      allowInput: (val) => !val || /^[-]?\d+(\.\d+)?$/.test(val),
      placeholder: '允许最小值',
      clearable: true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '步长',
    tag: 'n-input-number',
    tagType: 'Number',
    __vModel__: '__config__.step',
    __layout__: {},
    __config__: {
      placeholder: '请输入步长',
      clearable: true,
      buttonPlacement: 'both',
      min: 1,
      setp: 1,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '精度',
    tag: 'n-input-number',
    tagType: 'Number',
    __vModel__: '__config__.precision',
    __layout__: {},
    __config__: {
      placeholder: '请输入精度',
      clearable: true,
      buttonPlacement: 'both',
      min: 0,
      max: 9,
      setp: 1,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '显示按钮',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.showButton',
    __layout__: {},
    __config__: {
      'default-value': true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '按钮位置',
    tag: 'n-radio-group',
    tagType: 'Radio',
    __vModel__: '__config__.buttonPlacement',
    __layout__: {},
    __config__: {
      'default-value': 'right',
    },
    __slot__: {
      default: {
        type: 'button',
        space: {},
        options: [
          {
            value: 'both',
            label: '两边',
          },
          {
            value: 'right',
            label: '右侧',
          },
        ],
      },
    },
    __rules__: [],
  },
  {
    label: '显示边框',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.bordered',
    __layout__: {},
    __config__: {
      'default-value': true,
    },
    __slot__: {},
    __rules__: [],
  },
  {
    label: '能否清空',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.clearable',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
  {
    label: '是否只读',
    tag: 'n-switch',
    tagType: 'Switch',
    __vModel__: '__config__.readonly',
    __layout__: {},
    __config__: {},
    __slot__: {},
    __rules__: [],
  },
];
